require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrayersController do

  # This should return the minimal set of attributes required to create a valid
  # Prayer. As you add validations to Prayer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrayersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prayers as @prayers" do
      prayer = Prayer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prayers).should eq([prayer])
    end
  end

  describe "GET show" do
    it "assigns the requested prayer as @prayer" do
      prayer = Prayer.create! valid_attributes
      get :show, {:id => prayer.to_param}, valid_session
      assigns(:prayer).should eq(prayer)
    end
  end

  describe "GET new" do
    it "assigns a new prayer as @prayer" do
      get :new, {}, valid_session
      assigns(:prayer).should be_a_new(Prayer)
    end
  end

  describe "GET edit" do
    it "assigns the requested prayer as @prayer" do
      prayer = Prayer.create! valid_attributes
      get :edit, {:id => prayer.to_param}, valid_session
      assigns(:prayer).should eq(prayer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prayer" do
        expect {
          post :create, {:prayer => valid_attributes}, valid_session
        }.to change(Prayer, :count).by(1)
      end

      it "assigns a newly created prayer as @prayer" do
        post :create, {:prayer => valid_attributes}, valid_session
        assigns(:prayer).should be_a(Prayer)
        assigns(:prayer).should be_persisted
      end

      it "redirects to the created prayer" do
        post :create, {:prayer => valid_attributes}, valid_session
        response.should redirect_to(Prayer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prayer as @prayer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prayer.any_instance.stub(:save).and_return(false)
        post :create, {:prayer => { "title" => "invalid value" }}, valid_session
        assigns(:prayer).should be_a_new(Prayer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prayer.any_instance.stub(:save).and_return(false)
        post :create, {:prayer => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prayer" do
        prayer = Prayer.create! valid_attributes
        # Assuming there are no other prayers in the database, this
        # specifies that the Prayer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prayer.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => prayer.to_param, :prayer => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested prayer as @prayer" do
        prayer = Prayer.create! valid_attributes
        put :update, {:id => prayer.to_param, :prayer => valid_attributes}, valid_session
        assigns(:prayer).should eq(prayer)
      end

      it "redirects to the prayer" do
        prayer = Prayer.create! valid_attributes
        put :update, {:id => prayer.to_param, :prayer => valid_attributes}, valid_session
        response.should redirect_to(prayer)
      end
    end

    describe "with invalid params" do
      it "assigns the prayer as @prayer" do
        prayer = Prayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => prayer.to_param, :prayer => { "title" => "invalid value" }}, valid_session
        assigns(:prayer).should eq(prayer)
      end

      it "re-renders the 'edit' template" do
        prayer = Prayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => prayer.to_param, :prayer => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prayer" do
      prayer = Prayer.create! valid_attributes
      expect {
        delete :destroy, {:id => prayer.to_param}, valid_session
      }.to change(Prayer, :count).by(-1)
    end

    it "redirects to the prayers list" do
      prayer = Prayer.create! valid_attributes
      delete :destroy, {:id => prayer.to_param}, valid_session
      response.should redirect_to(prayers_url)
    end
  end

end
